### PR TITLE
install-macos-nix-grpc: link libgpr too

### PR DESCRIPTION
**Pull request by fumieval**
This is needed to build grpc-haskell on my environment

### CODE REVIEW

**Review by riz0id — APPROVED** [review]

**Comment by riz0id** [comment]
Thank you!

**Comment by ixmatus** [comment]
For a reason I cannot divine, the test suite appears to diverge on the macos tester...

**Comment by riz0id** [comment]
@fumieval are you using Nix to build `grpc-haskell`? If so, I believe #145 will fix the linking problems you're encountering when building `grpc-haskell` from within a Nix shell.

**Comment by fumieval** [comment]
No I'm not; I was simply trying to build it with plain cabal-install and `--extra-lib-dirs`

**Comment by fumieval** [comment]
By linking, I mean creating a symbolic link to libgpr.dylib

**Comment by fumieval** [comment]
@riz0id @ixmatus Is there anything I should do here? Is the build failure on Mac a blocker?

**Comment by ixmatus** [comment]
@fumieval we're pretty bogged down ATM and haven't had time to look at this. I don't think this is a blocker but something has happened recently causing the test to diverge on GitHub Action's macos builder.

**Comment by fumieval** [comment]
@ixmatus I understand your situation, but this is merely a one-line change to link libgpr.dylib. It doesn't affect anything but those who run bin/install-macos-nix-grpc.sh locally, so it would be nice if you could take a look and merge this.

**Pull request merged**
