### PR TITLE
nixpkgs upgrade

### PR DESCRIPTION
**Pull request by pshemass**

### CODE REVIEW

**Comment by Gabriel439** [comment]
@pshemass: Sorry for the delay.  I've been slowly working on fixing tests and pushed what I have so far:

https://github.com/awakesecurity/gRPC-haskell/compare/gabriel/fix_branch

... but there's still more work to be done

**Comment by pshemass** [comment]
@Gabriel439 let me know if I could help with those tests somehow?

**Comment by Gabriel439** [comment]
@pshemass: Feel free to merge my branch into yours if you want to incorporate the fixes I've made so far.  I've been testing on OS X so far and the current test output I get is:

```
Test suite tests: RUNNING...
GRPC Unit Tests
  Code generator tests
    server generation: clang-5.0: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
dyld: Library not loaded: libgrpc.dylib
  Referenced from: /Users/gabriel/proj/gRPC-haskell/tests/tmp/simple-server
  Reason: image not found
Starting python client
Test 100 random sums
Python client test exception caught: 
Common super type for exceptions indicating RPC abortion.

    initial_metadata: The initial metadata from the other side of the RPC or
      None if no initial metadata value was received.
    terminal_metadata: The terminal metadata from the other side of the RPC or
      None if no terminal metadata value was received.
    code: The code value from the other side of the RPC or None if no code value
      was received.
    details: The details value from the other side of the RPC or None if no
      details value was received.
  

Sending DONE message to server before exiting
Traceback (most recent call last):
  File "tests/test-client.py", line 79, in <module>
    stub.done(SimpleServiceDone(), 10)
  File "/nix/store/563j5c7c9sxwgcgb2qn7ng2cr1hnw1ad-python-2.7.15-env/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 324, in __call__
    self._request_serializer, self._response_deserializer)
  File "/nix/store/563j5c7c9sxwgcgb2qn7ng2cr1hnw1ad-python-2.7.15-env/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 210, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.ExpirationError: ExpirationError(code=StatusCode.DEADLINE_EXCEEDED, details="Deadline Exceeded")
FAIL (13.52s)
      tests/GeneratedTests.hs:41:
      expected: ExitSuccess
       but got: ExitFailure (-6)
    client generation: 
tests/TestClient.hs:42:35: warning: [-Wdeprecations]
    In the use of ‘assertString’
    (imported from Test.Tasty.HUnit, but defined in tasty-hunit-0.10.0.1:Test.Tasty.HUnit.Orig):
    Deprecated: "Why not use assertBool instead?"
   |
42 |        ClientErrorResponse err -> assertString ("ClientErrorResponse: " <> show err)
   |                                   ^^^^^^^^^^^^

tests/TestClient.hs:63:35: warning: [-Wdeprecations]
    In the use of ‘assertString’
    (imported from Test.Tasty.HUnit, but defined in tasty-hunit-0.10.0.1:Test.Tasty.HUnit.Orig):
    Deprecated: "Why not use assertBool instead?"
   |
63 |        ClientErrorResponse err -> assertString ("ClientErrorResponse: " <> show err)
   |                                   ^^^^^^^^^^^^

tests/TestClient.hs:64:48: warning: [-Wdeprecations]
    In the use of ‘assertString’
    (imported from Test.Tasty.HUnit, but defined in tasty-hunit-0.10.0.1:Test.Tasty.HUnit.Orig):
    Deprecated: "Why not use assertBool instead?"
   |
64 |        ClientWriterResponse Nothing _ _ _ _ -> assertString "No response received"
   |                                                ^^^^^^^^^^^^

tests/TestClient.hs:77:29: warning: [-Wdeprecations]
    In the use of ‘assertString’
    (imported from Test.Tasty.HUnit, but defined in tasty-hunit-0.10.0.1:Test.Tasty.HUnit.Orig):
    Deprecated: "Why not use assertBool instead?"
   |
77 |                 Left err -> assertString ("recv error: " <> show err)
   |                             ^^^^^^^^^^^^

tests/TestClient.hs:79:35: warning: [-Wdeprecations]
    In the use of ‘assertString’
    (imported from Test.Tasty.HUnit, but defined in tasty-hunit-0.10.0.1:Test.Tasty.HUnit.Orig):
    Deprecated: "Why not use assertBool instead?"
   |
79 |                 Right (Just _) -> assertString "recv: elements past end of stream"
   |                                   ^^^^^^^^^^^^

tests/TestClient.hs:83:29: warning: [-Wdeprecations]
    In the use of ‘assertString’
    (imported from Test.Tasty.HUnit, but defined in tasty-hunit-0.10.0.1:Test.Tasty.HUnit.Orig):
    Deprecated: "Why not use assertBool instead?"
   |
83 |                 Left err -> assertString ("recv error: " <> show err)
   |                             ^^^^^^^^^^^^

tests/TestClient.hs:84:34: warning: [-Wdeprecations]
    In the use of ‘assertString’
    (imported from Test.Tasty.HUnit, but defined in tasty-hunit-0.10.0.1:Test.Tasty.HUnit.Orig):
    Deprecated: "Why not use assertBool instead?"
   |
84 |                 Right Nothing -> assertString ("recv: stream ended earlier than expected")
   |                                  ^^^^^^^^^^^^

tests/TestClient.hs:93:35: warning: [-Wdeprecations]
    In the use of ‘assertString’
    (imported from Test.Tasty.HUnit, but defined in tasty-hunit-0.10.0.1:Test.Tasty.HUnit.Orig):
    Deprecated: "Why not use assertBool instead?"
   |
93 |        ClientErrorResponse err -> assertString ("ClientErrorResponse: " <> show err)
   |                                   ^^^^^^^^^^^^

tests/TestClient.hs:107:29: warning: [-Wdeprecations]
    In the use of ‘assertString’
    (imported from Test.Tasty.HUnit, but defined in tasty-hunit-0.10.0.1:Test.Tasty.HUnit.Orig):
    Deprecated: "Why not use assertBool instead?"
    |
107 |                 Left err -> assertString ("recv error: " <> show err)
    |                             ^^^^^^^^^^^^

tests/TestClient.hs:119:35: warning: [-Wdeprecations]
    In the use of ‘assertString’
    (imported from Test.Tasty.HUnit, but defined in tasty-hunit-0.10.0.1:Test.Tasty.HUnit.Orig):
    Deprecated: "Why not use assertBool instead?"
    |
119 |        ClientErrorResponse err -> assertString ("ClientErrorResponse: " <> show err)
    |                                   ^^^^^^^^^^^^
clang-5.0: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
dyld: Library not loaded: libgrpc.dylib
  Referenced from: /Users/gabriel/proj/gRPC-haskell/tests/tmp/simple-client
  Reason: image not found
Starting python server
Traceback (most recent call last):
  File "tests/test-server.py", line 41, in <module>
    done_queue.get(True, 10)
  File "/nix/store/563j5c7c9sxwgcgb2qn7ng2cr1hnw1ad-python-2.7.15-env/lib/python2.7/Queue.py", line 176, in get
    raise Empty
Queue.Empty
FAIL (13.71s)
      tests/GeneratedTests.hs:69:
      expected: ExitSuccess
       but got: ExitFailure 1

2 out of 2 tests failed (27.23s)
Test suite tests: FAIL
Test suite logged to: dist/test/grpc-haskell-0.0.0.0-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
```

The key bit is:

```
dyld: Library not loaded: libgrpc.dylib
  Referenced from: /Users/gabriel/proj/gRPC-haskell/tests/tmp/simple-server
  Reason: image not found
```

... which I'm still debugging.  I believe we fixed a similar issue internally, which I'm looking into.

**Comment by neongreen** [comment]
@Gabriel439 any hints? I'm stuck with the same `Library not loaded: libgrpc.dylib` issue.

**Comment by neongreen** [comment]
Found a fix: you have to use `fixDarwinDylibNames` (like here: https://github.com/NixOS/nixpkgs/commit/af2cfc076f8dd9c3583a8df1682a6d4602f7a9b6).

**Comment by ixmatus** [comment]
Superseded by #84.

**Pull request closed without merging**
