### PR TITLE
relax the upper bound for bytestring

### PR DESCRIPTION
**Pull request by fumieval**

### CODE REVIEW

**Review by riz0id — APPROVED** [review]
Thank you!

**Comment by ixmatus** [comment]
For a reason I cannot divine, the test suite appears to diverge on the macos tester...

**Comment by fumieval** [comment]
Is there anything I should do about this?

**Comment by ixmatus** [comment]
@fumieval I'm going to re-run the test suite on the macos builder but I'm not confident about it. Your change here is pretty innocuous so I don't think it's the culprit but I also don't have any time at the moment to debug why GitHub action runners on macos are diverging with our test suite.

If this rerun passes then we can conclude it was GitHub action's fault, otherwise we might have to figure out which test is diverging.

**Pull request merged**
