### PR TITLE
Fix build on GHC 8.4

### PR DESCRIPTION
**Pull request by devwout**

### CODE REVIEW

**Comment by Gabriel439** [comment]
Thank you for fixing that! Great work :)

**Comment by Gabriel439** [comment]
I just realized that we don't have CI set up for this project.  Let me take a brief stab at getting it going quickly

**Comment by Gabriel439** [comment]
I created a pull request to add Travis CI, but I also tested your change locally and it builds so I'll go ahead and merge

**Comment by devwout** [comment]
Awesome, thanks for the quick response!

**Comment by Gabriel439** [comment]
You're welcome! 🙂

**Pull request merged**
